[package]
name = "ble-audio-xiao-rp2350"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"
publish = false

[workspace]
resolver = "2"

[features]
default = []
usb-test-tone = []

[dependencies]
ble-audio-link = { path = "../../crates/audio-link" }
ble-audio-uac-descriptor = { path = "../../crates/uac-descriptor" }
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7"
defmt = "1"
defmt-rtt = "1"
embassy-executor = { git = "https://github.com/LegitCamper/embassy", rev = "760eb3b8d4725432588d4ee54ebaaa10f012a564", features = [
  "arch-cortex-m",
  "executor-thread",
  "defmt",
] }
embassy-rp = { git = "https://github.com/LegitCamper/embassy", rev = "760eb3b8d4725432588d4ee54ebaaa10f012a564", features = [
  "defmt",
  "unstable-pac",
  "time-driver",
  "critical-section-impl",
  "rp235xa",
] }
embassy-sync = { git = "https://github.com/LegitCamper/embassy", rev = "760eb3b8d4725432588d4ee54ebaaa10f012a564", features = [
  "defmt",
] }
embassy-time = { git = "https://github.com/LegitCamper/embassy", rev = "760eb3b8d4725432588d4ee54ebaaa10f012a564", features = [
  "defmt",
  "defmt-timestamp-uptime",
] }
embassy-usb = { git = "https://github.com/LegitCamper/embassy", rev = "760eb3b8d4725432588d4ee54ebaaa10f012a564", features = [
  "defmt",
] }
embassy-usb-driver = { git = "https://github.com/LegitCamper/embassy", rev = "760eb3b8d4725432588d4ee54ebaaa10f012a564", features = [
  "defmt",
] }
embedded-io-async = "0.7"
lc3-codec = { version = "=0.2.0", default-features = false }
panic-probe = { version = "1", features = ["print-defmt"] }
portable-atomic = { version = "1", features = ["critical-section"] }
static_cell = "2"

[lints.rust]
future-incompatible = "warn"
missing-docs = "warn"
nonstandard-style = "deny"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = false
overflow-checks = false
