//! Regenerate the local decoder tables using the firmware's no_std math implementation.
use num_traits::real::Real;

fn write_table(name: &str, values: &[f32]) {
    println!("#[rustfmt::skip]");
    println!("pub(super) const {name}: [f32; {}] = [", values.len());
    for row in values.chunks(4) {
        print!("    ");
        for (index, value) in row.iter().enumerate() {
            if index != 0 {
                print!(" ");
            }
            print!("f32::from_bits(0x{:08x}),", value.to_bits());
        }
        println!();
    }
    println!("];");
}

fn main() {
    println!("// Local modification: generated by examples/generate_decoder_tables.rs.");
    println!("// Keep the original f32 rounding and num-traits/libm evaluation.\n");
    let reflection = core::array::from_fn::<_, 17, _>(|index| {
        if index == 0 {
            0.0 // Preserve the upstream zero-index sentinel.
        } else {
            Real::sin((core::f64::consts::PI / 17.0) as f32 * (index as i32 - 8) as f32)
        }
    });
    write_table("REFLECTION_COEFFICIENTS", &reflection);
    println!();

    // gg_ind is 0..=255 and gg_off is -245..=-110 for the five sampling indices.
    let gains = core::array::from_fn::<_, 391, _>(|index| Real::powf(10.0_f32, (index as i32 - 245) as f32 / 28.0));
    write_table("GLOBAL_GAIN", &gains);
}
